# Generated by Django 3.2.5 on 2021-07-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
